apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: klusters.viveksingh.dev
spec:
  group: viveksingh.dev
  names:
    kind: Kluster
    listKind: KlusterList
    plural: klusters
    singular: kluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    deprecated: true
    deprecationWarning: "Kluster resources from v1alpha1 versions are deprecated"
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              nodes:
                type: array
                items:
                  type: string
  - name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              nodes:
                type: array
                items:
                  type: object
                  properties:
                    sizeSlug:
                      type: string
                    quantity:
                      type: integer